"""
Generate sample content output for Lotus Spa based on the calendar.
- File 1: social_posts (Facebook 12 bài + Zalo OA 4 bài) — 15-col format
- File 2: video_scripts (TikTok 8 video) — 13-col format
"""
import sys, os, unittest.mock as mock

for mod in ['supabase', 'asyncpg', 'storage', 'storage.session', 'storage.models',
            'storage.session_storage', 'agents', 'agents.skills', 'agents.pipeline',
            'agents.task_registry', 'config', 'frameworks', 'frameworks.kpi_library']:
    sys.modules[mod] = mock.MagicMock()

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from bot.renderers import render_excel_file

class OutputFormat:
    OPERATIONAL_DELIVERABLE = "operational_deliverable"

# ─────────────────────────────────────────────────────────────────
# SOCIAL POSTS — Facebook (12 bài) + Zalo OA (4 bài)
# ─────────────────────────────────────────────────────────────────
SOCIAL_POSTS = """\
## 🎯 Tóm tắt nhanh
- Đã viết 16 bài: 12 Facebook + 4 Zalo OA
- Pillar mix: Educate 5 · Trust 5 · Engage 3 · Convert 3
- Angle nổi bật: before/after thật; góc nhìn chuyên gia insider; đồng cảm mua hoài không thấy
- Tone: thân thiện, ấm áp, chân thật — tránh quảng cáo quá lộ

## 📄 Bảng nội dung đầy đủ

| Ngày | Thứ | Kênh | Content Pillar | Source Type | Hook (≤125 ký tự) | Body / Caption | CTA | Ghi chú Visual | Giờ đăng | KPI Target | Status | Người thực hiện | Link post | Ghi chú |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
| 02/01 | Thứ 5 | Facebook | Educate | Brand | "Da mùa đông cần gì khác ngày thường? Hầu hết mọi người đang bỏ qua bước quan trọng nhất." | Mùa đông da thường bị mất nước nhiều hơn bạn nghĩ — không phải vì không dưỡng ẩm, mà vì dưỡng ẩm sai thứ tự. Đây là 3 điều Lotus hay gặp nhất ở khách đến lần đầu: 1. Dùng serum trước toner (khóa ẩm sai lớp) / 2. Bỏ qua dầu dưỡng — lớp "khóa" quan trọng nhất mùa lạnh / 3. Rửa mặt nước quá nóng — phá vỡ hàng rào bảo vệ da. Mùa này da cần được giữ ấm từ bên trong, không chỉ thoa kem bên ngoài. Đông y có cách nhìn khác: da khô mùa đông thường liên quan đến tình trạng thiếu huyết khí — bổ từ bên trong mới giải quyết gốc rễ. Bạn đang gặp vấn đề gì với da mùa này? | Comment "DA" để em tư vấn thứ tự skincare đúng | Ảnh flat lay: toner + serum + dầu dưỡng xếp theo thứ tự đúng; nền gỗ ấm | 08:30 | | Draft | Content writer | | TOFU |
| 04/01 | Thứ 7 | Facebook | Trust | Brand | "5 năm làm spa Đông y, điều em học được không có trong sách giáo khoa nào." | Năm 2019, em mở Lotus với 1 phòng trị liệu và 0 khách quen. Khách đầu tiên là chị văn phòng 34 tuổi — nám 3 năm, đã thử 4 spa, đã dùng laser 2 lần, vẫn không hết. Em không dám hứa gì. Chỉ nói: mình cùng kiên nhẫn thử 2 tháng. Tháng 1 da chị sáng lên nhưng nám vẫn còn. Tháng 2 chị nhắn: "Chị không dám tin nữa." Kèm ảnh. Em cất ảnh đó đến giờ — không phải để marketing, mà để nhớ lý do mình làm nghề này. 5 năm qua, Lotus đã gặp hàng trăm ca như chị. Mỗi ca dạy em một điều mà không trường nào dạy được. Điều quan trọng nhất em học: da không bao giờ nói dối. Nó phản chiếu chính xác điều đang xảy ra bên trong cơ thể. | Comment "LOTUS" để xem hành trình 5 năm đầy đủ | Ảnh founder (chủ spa) nhìn vào kính, ánh sáng vàng ấm; phong cách editorial tự nhiên | 09:00 | | Draft | Brand | | TOFU |
| 07/01 | Thứ 3 | Facebook | Engage | Brand | "Bạn đang gặp vấn đề da nào nhất mùa đông này? Em muốn nghe thật." | Da mùa đông — mỗi người một kiểu khổ khác nhau. Có người khô bong tróc dù thoa kem liên tục. Có người nổi mụn ẩn hàng loạt dù không ăn gì lạ. Có người nám tối hơn hẳn dù không ra nắng. Có người da căng rát như bị kéo, đặc biệt sau khi rửa mặt. Em hỏi vì muốn hiểu bạn đang gặp vấn đề gì thật sự — không phải để bán, mà để chia sẻ đúng thứ bạn cần. Tuần này em sẽ trả lời từng comment cụ thể. Không copy-paste, không tư vấn chung chung. | Comment vấn đề da của bạn — em trả lời cụ thể trong 24h | Ảnh 4 icon đại diện 4 vấn đề da (khô / mụn / nám / căng rát) trên nền trắng tối giản | 20:00 | | Draft | Brand | | TOFU |
| 09/01 | Thứ 6 | Facebook | Educate | Brand | "Vì sao serum 2 triệu không hiệu quả hơn serum 200k? Câu trả lời không phải về thành phần." | Có một sự thật brand không bao giờ nói với bạn: 80% hiệu quả của skincare đến từ CÁCH dùng, không phải sản phẩm. Serum đắt tiền mà layer sai thứ tự — uổng. Kem chống nắng tốt mà thoa không đủ lượng — không bảo vệ được. Retinol xịn mà dùng ban ngày — hại da. Đông y có nguyên tắc tương tự: thảo dược quý đến đâu, sắc sai cách hoặc uống sai giờ — không hiệu quả, thậm chí phản tác dụng. Dưới đây là 5 lỗi sai phổ biến nhất em gặp khi tư vấn khách — không phân biệt skincare rẻ hay đắt: 1. Dùng AHA/BHA cùng Vitamin C buổi sáng / 2. Thoa retinol trên da ẩm (tăng kích ứng) / 3. Bỏ qua toner trước serum / 4. Thoa SPF quá mỏng — cần 2 ngón tay mới đủ / 5. Mix quá nhiều active cùng lúc. Bạn đang mắc lỗi nào không? | Comment số lỗi bạn đang mắc — em giải thích cách sửa | Carousel 5 slide, mỗi slide 1 lỗi với icon minh họa đơn giản; màu pastel ấm | 11:30 | | Draft | Content writer | | MOFU |
| 12/01 | Thứ 2 | Facebook | Trust | Brand | "Đây là điều chị Lan Anh nhắn em sau 3 tháng điều trị nám tại Lotus. Em xin phép chia sẻ." | "Hồi tháng 9 mình đến Lotus với tâm lý thử cho biết, không kỳ vọng gì vì đã thất vọng nhiều lần rồi. Mình đã laser 2 lần, dùng đủ loại serum nám, uống collagen 6 tháng — nám vẫn còn. Bạn tư vấn viên hỏi mình về giấc ngủ, về stress, về chế độ ăn — lần đầu tiên mình thấy spa quan tâm đến điều đó. 3 tháng trị liệu kết hợp Đông y + chăm sóc tại chỗ, mình giảm được 70% vết nám. Không kỳ diệu gì — chỉ là lần đầu tiên trị đúng nguyên nhân." — Lan Anh, 36 tuổi, văn phòng Q1. Em không bịa. Không chỉnh ảnh. Chỉ xin phép đăng lại lời chị nói. Có câu hỏi gì về quy trình điều trị nám tại Lotus, em trả lời thẳng thắn. | Inbox "NÁM" để em tư vấn quy trình phù hợp với da bạn | Ảnh trước/sau thật của chị Lan Anh (che nhận dạng nếu cần); ánh sáng tự nhiên, không chỉnh màu | 09:00 | | Draft | Brand | | MOFU |
| 14/01 | Thứ 4 | Facebook | Educate | Brand | "Quy trình 5 bước tại Lotus Spa — em chia sẻ để bạn hiểu mình đang làm gì với da của mình." | Nhiều khách hỏi: trị liệu Đông y tại Lotus khác spa thông thường chỗ nào? Em giải thích thẳng. Bước 1 — Thăm khám tổng thể (20 phút): Không chỉ nhìn da — kiểm tra lưỡi, mạch, hỏi về giấc ngủ, chu kỳ, stress. Da là gương của nội tạng. / Bước 2 — Phân loại tạng thể: Da khô do hư huyết khác da khô do nhiệt. Điều trị khác nhau hoàn toàn. / Bước 3 — Liệu trình Đông y: Thảo dược tươi sắc ngày, đắp lạnh đặc biệt theo tạng thể. Không máy móc, không sóng. / Bước 4 — Massage kinh lạc: Khai thông 14 đường kinh, tăng tuần hoàn nuôi da từ sâu bên trong. / Bước 5 — Hướng dẫn tại nhà: Không bán gói sản phẩm. Chỉ chỉ cách điều chỉnh thói quen ăn uống, ngủ, skincare phù hợp tạng thể. Đó là lý do Lotus không thể trị nhanh — nhưng khi trị, là trị thật. | Comment "QUY TRÌNH" để em gửi chi tiết từng bước | Infographic 5 bước đẹp, màu xanh lá Đông y; ảnh nhỏ minh họa từng bước | 14:00 | | Draft | Content writer | | MOFU |
| 16/01 | Thứ 6 | Facebook | Engage | Brand | "Câu hỏi em hay nhận nhất: liệu trình bao lâu mới thấy kết quả? Em trả lời thật." | Em hiểu câu hỏi này — vì ai cũng đã từng bỏ tiền mà không thấy kết quả. Câu trả lời trung thực: Tùy vấn đề và tạng thể của mỗi người. Nhưng em có thể nói cụ thể hơn: Da thường (chăm sóc cơ bản): 2-3 buổi thấy da mịn, sáng hơn. Nám nhẹ (mới xuất hiện dưới 1 năm): 6-8 buổi thấy nhạt rõ. Nám sâu (trên 2-3 năm, đã laser): 12-16 buổi, kết hợp điều chỉnh nội tiết. Mụn viêm cấp: 3-4 buổi giảm viêm, 8-10 buổi ổn định. Em không hứa kết quả cụ thể vì mỗi người một tạng thể. Nhưng em hứa: sau buổi đầu tiên bạn sẽ biết mình phù hợp không, trước khi quyết định gói dài. | Comment vấn đề da cụ thể — em estimate timeline riêng cho bạn | Ảnh câu hỏi to rõ trên nền màu, thiết kế đơn giản | 20:00 | | Draft | Brand | | MOFU |
| 19/01 | Thứ 2 | Facebook | Trust | Brand | "Khách đăng review tự nhiên không nhờ vả, không thưởng — em xin phép repost lại." | [REPOST VIDEO TIKTOK CỦA KHÁCH] Em không dàn dựng, không nhờ quay, không trả thù lao. Chị tự quay, tự đăng, tự tag Lotus. Đây là loại review em trân trọng nhất — vì nó thật. Nếu bạn đang phân vân có nên thử Lotus không, có thể inbox em để nghe thêm từ những khách đang điều trị. Em sẵn sàng kết nối — không phải để thuyết phục, mà để bạn có đủ thông tin quyết định. | Inbox "REVIEW" để em kết nối với khách cũ | Repost video organic của khách — giữ nguyên, không chỉnh sửa | 09:30 | | Draft | Brand | | MOFU |
| 21/01 | Thứ 4 | Facebook | Convert | Brand | "Combo Tết 680K (gốc 850K) — còn 10 slot trong tháng 1. Em giải thích tại sao không phải khuyến mãi thông thường." | Lotus không hay làm flash sale. Lần này em quyết định vì 1 lý do: Tết là thời điểm nhiều bạn muốn "reset" da trước khi về nhà, trước khi gặp họ hàng, trước khi chụp ảnh Tết. Em hiểu cảm giác đó. Combo Tết 680K bao gồm: 1 buổi thăm khám + phân loại tạng thể (trị giá 150K) / 1 liệu trình trị liệu Đông y 90 phút (trị giá 450K) / 1 set hướng dẫn skincare tại nhà theo tạng thể (trị giá 250K). Tổng thật: 850K. Em giảm còn 680K — tiết kiệm 170K. Tại sao 10 slot? Vì mỗi buổi thăm khám mất 20 phút, em chỉ có thể nhận 10 ca mới trong tháng mà vẫn đảm bảo chất lượng cho khách cũ. Không phải chiêu marketing. Là giới hạn thật của lịch em. | Inbox "TẾT" để đặt lịch — em xác nhận slot trong 2 giờ | Ảnh sản phẩm + voucher combo đẹp; màu đỏ vàng Tết nhẹ, không lòe loẹt | 11:00 | | Draft | Brand | | BOFU |
| 23/01 | Thứ 6 | Facebook | Trust | Brand | "Khách VIP của Lotus — em muốn nói điều này trước Tết." | Với những ai đã đồng hành cùng Lotus từ năm 2021, 2022 — em muốn nói thẳng: Năm nay Lotus sẽ ưu tiên giữ slot cho các khách cũ trước khi nhận khách mới. Đây không phải thông báo marketing — đây là cam kết em giữ từ ngày mở. Ai cần đặt lịch Tết (20/01 - 28/01), inbox em trước 22/01 — em sắp xếp ưu tiên. Không cần combo, không cần deal. Chỉ cần nhắn "đặt lịch" là em lo. Cảm ơn bạn đã tin Lotus trong những năm qua. Mỗi case bạn chia sẻ với em đều là bài học em mang theo. | Inbox "VIP" để đặt lịch ưu tiên | Ảnh bàn tay cầm phong bì đỏ Tết; nền ấm áp; không có logo to | 09:00 | | Draft | Brand | | BOFU |
| 26/01 | Thứ 2 | Facebook | Convert | Brand | "Còn 3 ngày — 5 slot combo Tết cuối cùng. Không nhận thêm sau 28/01." | Em không muốn tạo urgency giả. Đây là thật: Hôm nay 26/01. Lotus đóng cửa nghỉ Tết từ 29/01. Còn đúng 5 slot combo Tết 680K chưa có người đặt. Sau 28/01, em không nhận thêm — không phải vì hết deal, mà vì em cần chuẩn bị cho lịch tháng 2 của khách cũ. Nếu bạn đang phân vân từ hồi đầu tháng mà chưa quyết: đây là lần cuối em nhắc. Không inbox sau 28/01 thì xem lịch tháng 2 nhé. | Inbox "CHỐT" trước 28/01 — em xác nhận ngay | Đồng hồ đếm ngược đến 28/01; thiết kế đơn giản, màu đỏ nhẹ | 08:30 | | Draft | Brand | | BOFU |
| 28/01 | Thứ 4 | Facebook | Engage | Brand | "Tháng 1 của Lotus kết thúc ở đây — cảm ơn bạn đã cùng em đi qua 28 ngày này." | Tháng 1/2026 — Lotus phục vụ 47 khách. 12 ca mới, 35 ca tái khám. 3 ca nám đã kết thúc liệu trình, đang duy trì. 1 ca viêm da cơ địa lần đầu tiên ngủ ngon sau 2 năm. 2 ca trị mụn nội tiết thấy chu kỳ ổn định lại. Em không đăng số để khoe. Em đăng để nhớ. Mỗi con số là 1 người thật, 1 câu chuyện thật, 1 buổi sáng ngủ dậy nhìn gương và thấy mình khác đi. Tháng 2 Lotus mở lịch từ 03/02 sau Tết. Ai muốn đặt lịch sớm — inbox em trước 30/01 để ưu tiên giữ slot. Chúc bạn Tết ấm áp. Hẹn gặp lại. | Inbox "THÁNG 2" để đặt lịch sau Tết | Ảnh tổng kết tháng đẹp; số liệu viết tay trên bảng gỗ; ánh sáng ấm vàng | 19:00 | | Draft | Brand | | BOFU |
| 05/01 | Chủ nhật | Zalo OA | Educate | Brand | "Tips chăm da mùa đông từ Lotus — quà đầu năm cho bạn." | Đầu năm mới, Lotus gửi bạn 3 tips chăm da mùa đông từ góc nhìn Đông y: 1. Uống nước ấm thay nước lạnh — giúp tỳ vị hấp thụ tốt hơn, da ẩm từ bên trong. 2. Ăn thêm vừng đen + hạt óc chó — bổ thận, nuôi da tóc móng mùa lạnh. 3. Ngủ trước 23h ít nhất 4 ngày/tuần — gan hoạt động 23h-1h sáng, ảnh hưởng trực tiếp đến màu da. Chúc bạn năm mới sức khỏe, da đẹp từ bên trong! | Inbox "TƯ VẤN" nếu bạn muốn em xem da cụ thể | Gửi kèm ảnh infographic 3 tips đẹp | 08:30 | | Draft | Brand | | MOFU |
| 12/01 | Thứ 2 | Zalo OA | Trust | Brand | "Lâu rồi chưa gặp bạn — da dạo này thế nào ạ?" | Dạ em là Lotus Spa. Em thấy bạn chưa quay lại khoảng 2 tháng nay. Không hối thúc — chỉ hỏi thăm thật. Mùa đông này da thường khó hơn, đặc biệt với những vấn đề cần duy trì đều. Nếu bạn đang bận hoặc đang thử cách khác thì hoàn toàn OK. Nếu bạn muốn check lại tình trạng da, Lotus có slot tuần này. Không cần đặt gói mới — em xem lại và tư vấn tiếp theo tình trạng hiện tại của bạn thôi. | Nhắn "CHECK DA" để em đặt lịch cho bạn | | 09:00 | | Draft | Brand | | MOFU |
| 20/01 | Thứ 3 | Zalo OA | Convert | Brand | "Bạn ơi — combo Tết 680K, Lotus ưu tiên báo khách cũ trước." | Dạ Lotus đang có combo trước Tết: 1 buổi thăm khám + liệu trình Đông y 90 phút + hướng dẫn skincare tại nhà — 680K (gốc 850K). Bạn là khách cũ nên em báo trước khi đăng công khai. Còn 8 slot, ưu tiên đặt trước 22/01. Bạn nhắn "ĐẶT LỊCH" là em confirm ngay ạ. | Nhắn "ĐẶT LỊCH" để giữ slot | | 11:00 | | Draft | Brand | | BOFU |
| 28/01 | Thứ 4 | Zalo OA | Engage | Brand | "Lotus nghỉ Tết từ 29/01 — cảm ơn bạn năm nay." | Dạ Lotus nghỉ Tết từ ngày mai 29/01, mở cửa trở lại 03/02 ạ. Cảm ơn bạn đã tin tưởng Lotus trong năm 2025. Mỗi lần bạn ghé là thêm 1 kỷ niệm em trân trọng. Chúc bạn Tết ấm áp, vui vẻ bên gia đình. Sức khỏe, bình an, và da đẹp từ bên trong nhé bạn! Hẹn gặp lại tháng 2. | | | 19:00 | | Draft | Brand | | VIP |
"""

# ─────────────────────────────────────────────────────────────────
# VIDEO SCRIPTS — TikTok (8 video)
# ─────────────────────────────────────────────────────────────────
VIDEO_SCRIPTS = """\
## 🎯 Tóm tắt nhanh
- Đã viết 8 kịch bản TikTok cho Lotus Spa tháng 1/2026
- Funnel mix: 3 TOFU · 3 MOFU · 2 BOFU
- Hook angle: tò mò x3 / đồng cảm x2 / góc nhìn chuyên gia x2 / trái ngược x1
- Tone: founder/nhân viên nói chuyện thật — không đọc script, không quá professional

## 📄 Bảng kịch bản đầy đủ

| Version | Creator Type | Platform | Hook 3s | Problem/Pain 10s | Solution 20s | Social Proof 10s | CTA 7s | Visual Direction | Music/SFX | Caption Hook | Hashtags | Ghi chú |
|---|---|---|---|---|---|---|---|---|---|---|---|---|
| V1 — 03/01 | Founder (nữ 30+) | TikTok | "Bạn có biết 80% người dưỡng ẩm mùa đông đang làm sai? Và cái sai đó khiến da khô hơn." | Mùa đông da bạn bong tróc dù thoa kem liên tục — không phải kem kém, mà bạn đang khóa ẩm sai lớp. Serum trước toner = serum không thẩm thấu được. Da mình cũng từng vậy. | Đây là thứ tự đúng: bước 1 toner ướt da, bước 2 serum khi da còn ẩm, bước 3 kem giữ ẩm khóa lại, bước 4 dầu dưỡng mùa lạnh là lớp cuối cùng. [Demo nhanh từng lớp trên tay] Thêm 1 bước Đông y: chườm khăn ấm 30 giây trước skincare — mở lỗ chân lông, tăng thẩm thấu gấp 3. | [Chèn review khách thật sau khi áp dụng đúng thứ tự] / Em tư vấn hàng trăm ca mùa đông — 9/10 người mắc lỗi thứ tự này. | Inbox "DA KHÔ" để em gửi thêm hướng dẫn chi tiết nhé. | Beat1: close-up mặt founder nhìn thẳng cam / Beat2: flat lay các bước skincare xếp theo thứ tự / Beat3: demo tay thoa từng lớp tốc độ bình thường / Beat4: time-lapse trước-sau 30 ngày | Nhạc: chill lo-fi nhẹ; SFX: tiếng "ding" ở mỗi bước | "Thứ tự skincare đúng mùa đông — cái bước thứ 4 ít người biết" | #skincareVietnam #chamda #muadong #lotus spa #dakhô #skincaretips #dongydacot #beautyVN | TOFU |
| V2 — 06/01 | Nhân viên spa (nữ 25-28) | TikTok | "Đây là 1 ngày bình thường tại Lotus Spa. Không filter. Không dàn dựng. Thật 100%." | Nhiều bạn hỏi em: làm spa Đông y trông như thế nào? Không phải nhạc chill, nến thơm, mặt nạ trắng như quảng cáo đâu nha. | [Follow cam nhân viên từ 8am] 8 giờ: chuẩn bị thảo dược tươi sắc ngày — mùi không giống nước hoa đâu nha, mùi... thuốc. 9 giờ: thăm khám ca đầu — nhìn lưỡi, bắt mạch, hỏi giấc ngủ. 10 giờ: trị liệu 90 phút — massage kinh lạc, đắp thảo dược. 12 giờ: ăn trưa 20 phút rồi lại tiếp. Đây là thật. Không màu hồng. Nhưng khi thấy da khách đổi thay từng tuần — đó là lý do bọn em làm. | "Hôm qua chị Hoa nhắn: 'Em ơi da chị không bong tróc nữa rồi.' Đó là ngày bình thường tuyệt nhất." | Theo dõi Lotus để thấy thêm hậu trường thật nhé! | Quay dọc theo nhân viên suốt ngày / Wide shot phòng trị liệu / Close-up tay chuẩn bị thảo dược / Ánh sáng tự nhiên cửa sổ | Nhạc: acoustic Việt nhẹ; không SFX | "1 ngày làm việc tại spa Đông y — không filter không dàn dựng" | #behindthescenes #spaVietnam #dongytrilieu #lotusspaq7 #authenticspa #beautyworker #daydiem | TOFU |
| V3 — 10/01 | Founder (nữ 30+) | TikTok | "3 điều Đông y làm được mà serum 2 triệu không làm được — số 2 ít người biết." | Bạn đã bao giờ đổ hết tủ skincare nhưng da vẫn không thay đổi? Không phải sản phẩm kém — là bạn đang điều trị bề mặt trong khi vấn đề nằm bên trong. | Điều 1: Đông y điều trị theo tạng thể — da khô do hư huyết khác da khô do nội nhiệt. Điều trị đúng nguyên nhân chứ không chữa triệu chứng. [Demo biểu đồ đơn giản] Điều 2: Kinh lạc ảnh hưởng đến da mặt. Đường kinh Can đi qua vùng nám. Đường kinh Phế ảnh hưởng lỗ chân lông. Massage đúng điểm = tác động đúng vùng. [Demo điểm huyệt trên mặt] Điều 3: Thảo dược tươi hấp thụ qua da tốt hơn sản phẩm qua chuỗi công nghiệp vì không có chất bảo quản. | [Chèn ảnh so sánh da khách trước-sau thật — xin phép trước] / Lotus đã gặp hàng trăm ca "skincare đủ kiểu vẫn không ổn" rồi trị khỏi bằng cách này. | Comment "ĐÔNG Y" để em giải thích cơ chế phù hợp với da bạn. | Split screen: tủ skincare đầy vs không gian trị liệu đơn giản / Diagram kinh lạc đơn giản trên face / Close-up thảo dược tươi | Nhạc: nhạc Á Đông nhẹ; SFX: tiếng nước sôi khi nói về sắc thảo dược | "Serum 2 triệu không làm được điều này — góc nhìn Đông y" | #dongytrilieu #skincarescience #namvietnam #lotusspaq7 #dongydacot #skincaretips #beautyVN #trainguoc | MOFU |
| V4 — 13/01 | Brand (dùng ảnh/clip khách) | TikTok | "Đây là ảnh chị Mai gửi em trước khi đến Lotus. Và đây là sau 2 tháng." | Chị nhắn: 'Em ơi, chị đã thử mọi thứ rồi. Laser 2 lần, serum nám 3 loại, kiêng nắng 6 tháng. Nám vẫn còn. Chị muốn thử lần cuối trước khi bỏ cuộc.' | Tháng 1: thăm khám — phát hiện chị thiếu ngủ kinh niên, stress cao, chu kỳ không đều. Nám không phải từ nắng — từ nội tiết mất cân bằng. Tháng 1-2: liệu trình kết hợp Đông y + điều chỉnh thói quen ngủ + ăn bổ huyết. Tháng 3: chị nhắn lại — kèm ảnh. [Show ảnh before-after thật, ánh sáng như nhau] | Đây không phải kỳ diệu. Đây là điều trị đúng nguyên nhân. Chị Mai đã đồng ý cho em chia sẻ câu chuyện. | Inbox "NÁM" nếu bạn đang trong tình huống giống chị Mai. | Slow reveal before-after / Text overlay câu chị nhắn / Close-up vùng nám trước và sau (zoom in) / Ánh sáng như nhau cả 2 ảnh — không chỉnh màu | Nhạc: nhẹ cảm xúc, không lời; SFX: tiếng chim khi reveal after | "Laser 2 lần vẫn còn nám — câu chuyện của chị Mai" | #namda #trịnam #lotusspaq7 #dongytrilieu #beforeafter #skincarestory #beautyVN #chamsocda | MOFU |
| V5 — 17/01 | Founder (nữ 30+) | TikTok | "Câu trả lời thật: liệu trình spa có thực sự cần thiết không? Kể cả khi câu trả lời là KHÔNG." | Mình biết bạn đang nghĩ gì: 'Spa nói spa thì cần, còn hỏi ai.' Nên mình sẽ trả lời thẳng thắn nhất có thể — kể cả khi nó không có lợi cho Lotus. | Không cần spa nếu: Da bạn bình thường, không có vấn đề đặc biệt, skincare tại nhà đang ổn. Tiết kiệm tiền. Cần spa nếu: Bạn đã thử nhiều cách nhưng vấn đề không giải quyết được (nám, mụn viêm tái phát, da nhạy cảm kinh niên). Vấn đề của bạn có liên quan đến nội tiết / giấc ngủ / stress — skincare ngoài da không đủ. Bạn muốn hiểu da mình đang nói gì thay vì chỉ che phủ. Spa không phải luxury. Spa là đầu tư khi cần đầu tư. | Lotus không nhận ca không cần trị. Em sẽ nói thẳng ngay buổi đầu nếu da bạn không cần liệu trình. | Comment câu hỏi về da bạn — em trả lời thật nhất có thể. | Founder nhìn thẳng cam / Chia đôi màn hình: "không cần" vs "cần" / Facial expression tự nhiên, không script | Nhạc: chill nhẹ; không SFX đặc biệt | "Spa có thực sự cần thiết không? Câu trả lời thật từ chủ spa" | #spa truth #lotusspaq7 #skincareadvice #chamsocda #beautyVN #honestbeauty #dongytrilieu | MOFU |
| V6 — 20/01 | UGC (khách thật) | TikTok | "Tôi không quay video này vì được nhờ. Tôi quay vì 60 ngày trước tôi gần như bỏ cuộc." | Hồi tháng 11, tôi đặt lịch Lotus với tâm lý: thử lần cuối rồi thôi. Đã tốn quá nhiều tiền và công sức cho làn da này rồi. | [Khách tự kể] Tôi không biết kỳ vọng gì. Chỉ biết tư vấn viên hỏi những câu không spa nào từng hỏi — ngủ mấy tiếng, ăn gì, stress kiểu gì. Lần đầu tiên tôi thấy ai đó nhìn da tôi như một phần của cơ thể, không phải bề mặt cần sửa. 2 tháng sau: nám nhạt 60%, da không còn bong tróc. Không kỳ diệu. Nhưng lần đầu tiên tôi cảm thấy đang trị đúng vấn đề. | [Khách show ảnh trước-sau] Tôi không được trả thù lao để đăng video này. Tôi đăng vì nếu bạn đang ở chỗ tôi hồi tháng 11, biết đâu video này giúp được. | [Không CTA cứng — để tự nhiên] | Khách tự quay dọc / Ánh sáng tự nhiên / Không dàn dựng / Có thể cầm điện thoại hơi run — OK | Nhạc: acoustic nhẹ; không SFX | "60 ngày trước tôi gần bỏ cuộc điều trị nám — đây là điều đã thay đổi" | #ugcreview #lotusspaq7 #namda #skincarejourney #realhonest #beautyVN #dongytrilieu #reviewthat | MOFU |
| V7 — 24/01 | Founder (nữ 30+) | TikTok | "Combo Tết 680K của Lotus có gì? Em breakdown thật — không phải để bán, để bạn tự quyết." | Mỗi dịp Tết em đều thấy nhiều spa tung deal rồi ghi chú nhỏ '* điều kiện áp dụng'. Em không muốn làm vậy. Nên em sẽ nói hết — kể cả điểm không hay. | Combo 680K bao gồm: Thăm khám Đông y 20 phút (bình thường 150K) + Liệu trình trị liệu 90 phút (bình thường 450K) + Set hướng dẫn tại nhà theo tạng thể (bình thường 250K). Tổng thật 850K — giảm 170K. Không hay ở chỗ nào? Slot có hạn — em chỉ nhận 10 ca mới tháng này. Nếu bạn đặt rồi cancel không báo trước 24h — slot đó mất, em không refund. Phù hợp nhất cho ai: lần đầu muốn thử Đông y, hoặc muốn check lại da trước Tết mà chưa biết bắt đầu từ đâu. | [Chèn 2-3 feedback khách đã dùng combo tháng trước] | Inbox "TẾT" nếu bạn muốn đặt — em trả lời trong 2 tiếng. | Founder cầm điện thoại nói chuyện thẳng / Text overlay từng hạng mục combo / Màu đỏ vàng Tết nhẹ ở góc | Nhạc: Tết nhẹ không quá truyền thống; SFX: "ding" ở mỗi hạng mục | "Breakdown thật combo Tết 680K — kể cả điểm không hay" | #tetsale #lotusspaq7 #dongytrilieu #combotết #beautyVN #transparent #skincaresale | BOFU |
| V8 — 27/01 | Brand | TikTok | "Còn đúng 3 ngày. 5 slot cuối. Lotus đóng cửa 29/01." | Không drama. Không đếm ngược giả. Thật là: hôm nay 27/01, Lotus đóng cửa nghỉ Tết 29/01. | [Text overlay đơn giản] Combo Tết 680K còn 5 slot chưa có người đặt. Sau 28/01 em không nhận thêm — không phải vì hết ưu đãi, mà vì lịch tháng 2 của khách cũ cần ưu tiên trước. Nếu bạn đang phân vân từ đầu tháng: đây là lần cuối em nhắc. | [Chèn số đã đặt: "XX người đã đặt trong tháng này"] | Inbox "CHỐT" trước 28/01. Em confirm ngay. | Text trắng trên nền đỏ Tết đơn giản / Countdown timer thật / Không cần quay người | Nhạc: Tết nhẹ fade out; SFX: tiếng đồng hồ tick ở cuối | "Còn 3 ngày — 5 slot Tết cuối cùng của Lotus" | #lastchance #lotusspaq7 #combotết #beautyVN #tetsale #dongspa #countdown | BOFU |
"""


def render(skill_name, skill_label, mock_text, out_path):
    parsed = {"deliverable": mock_text, "summary": "", "raw": mock_text}
    xlsx = render_excel_file(
        skill_name=skill_name,
        skill_label=skill_label,
        parsed=parsed,
        output_format=OutputFormat.OPERATIONAL_DELIVERABLE,
        business_name="Lotus Spa",
    )
    if xlsx:
        with open(out_path, "wb") as f:
            f.write(xlsx)
        print(f"  {out_path} ({len(xlsx):,} bytes)")
    else:
        print(f"  FAILED: {out_path}")


def main():
    base = "/home/user/marketing-os-bot"
    print("Rendering...")
    render("social_posts",   "Bài Đăng",        SOCIAL_POSTS,   f"{base}/sample_lotus_social_posts.xlsx")
    render("video_script_gen","Kịch Bản Video",  VIDEO_SCRIPTS,  f"{base}/sample_lotus_video_scripts.xlsx")
    print("Done.")


if __name__ == "__main__":
    main()
