"""
HTML report generator for Marketing OS analysis output.
Bundles structured agent outputs into 1 styled HTML document.
"""
import re
from datetime import datetime

try:
    import markdown as _md
    HAS_MARKDOWN = True
except ImportError:
    HAS_MARKDOWN = False


STAGE_META = {
    "market_research":    {"title": "Nghiên cứu Thị trường",       "icon": "📊", "color": "market"},
    "competitor":         {"title": "Phân tích Đối thủ",            "icon": "🕵️", "color": "competitor"},
    "customer_insight":   {"title": "Customer Insight & ICP",      "icon": "👥", "color": "customer"},
    "psychology_pricing": {"title": "Marketing Psychology & Pricing", "icon": "💡", "color": "pricing"},
    "social_listening":   {"title": "Social Listening System",     "icon": "📡", "color": "market"},
    "synthesis":          {"title": "Marketing Strategy",          "icon": "🚀", "color": "strategy"},
}


CSS = """
:root {
  --primary: #2563eb; --accent: #f59e0b; --bg: #fafafa; --card: #ffffff;
  --text: #1e293b; --muted: #64748b; --border: #e2e8f0;
  --success: #10b981;
}
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  background: var(--bg); color: var(--text); line-height: 1.65; padding: 24px 16px;
}
.container { max-width: 880px; margin: 0 auto; }
.header {
  background: linear-gradient(135deg, #2563eb 0%, #7c3aed 100%);
  color: white; padding: 36px 32px; border-radius: 16px; margin-bottom: 24px;
  box-shadow: 0 4px 20px rgba(37,99,235,0.15);
}
.header h1 { font-size: 28px; font-weight: 700; margin-bottom: 8px; }
.header .meta { font-size: 14px; opacity: 0.9; }
.header .powered { margin-top: 16px; font-size: 12px; opacity: 0.7; }

.section {
  background: var(--card); border-radius: 12px; padding: 28px; margin-bottom: 20px;
  box-shadow: 0 1px 3px rgba(0,0,0,0.05); border-left: 4px solid var(--primary);
}
.section.market    { border-color: #2563eb; }
.section.competitor{ border-color: #f59e0b; }
.section.customer  { border-color: #10b981; }
.section.pricing   { border-color: #ec4899; }
.section.strategy  { border-color: #8b5cf6; }

.section-header {
  display: flex; align-items: center; gap: 12px;
  margin-bottom: 18px; padding-bottom: 12px; border-bottom: 1px solid var(--border);
}
.section-header .icon { font-size: 24px; }
.section-header h2 { font-size: 20px; font-weight: 600; }

.insight {
  background: #fef3c7; border-left: 4px solid var(--accent);
  padding: 14px 18px; border-radius: 6px; margin: 14px 0;
  font-style: italic; color: #78350f;
}
.insight::before { content: "💡 "; font-style: normal; }

.summary, .benchmarks {
  background: #f0f9ff; border-left: 3px solid var(--primary);
  padding: 14px 18px; border-radius: 8px; margin: 14px 0;
}
.summary-label, .benchmarks-label {
  font-size: 11px; font-weight: 600; text-transform: uppercase;
  color: var(--primary); letter-spacing: 0.5px; margin-bottom: 8px;
}

.content h1, .content h2, .content h3 { margin: 18px 0 10px; font-weight: 600; }
.content h1 { font-size: 20px; }
.content h2 { font-size: 18px; }
.content h3 { font-size: 16px; }
.content h4 { font-size: 14px; color: var(--muted); }
.content p { margin-bottom: 12px; }
.content ul, .content ol { margin: 8px 0 12px 24px; }
.content li { margin-bottom: 6px; }
.content strong { font-weight: 600; }
.content table {
  width: 100%; border-collapse: collapse; margin: 14px 0; font-size: 14px;
}
.content th, .content td {
  padding: 10px 14px; text-align: left; border-bottom: 1px solid var(--border);
}
.content th {
  background: #f1f5f9; font-weight: 600; font-size: 12px;
  text-transform: uppercase; color: var(--muted); letter-spacing: 0.5px;
}
.content tr:hover { background: #f8fafc; }
.content blockquote {
  border-left: 3px solid var(--accent); padding: 8px 14px; margin: 12px 0;
  background: #fffbeb; color: #78350f; font-style: italic;
}

.footer {
  text-align: center; color: var(--muted); font-size: 12px;
  padding: 24px 16px; margin-top: 16px;
}
"""


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="vi">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Marketing Report — {business_name}</title>
<style>{css}</style>
</head>
<body>
<div class="container">

  <div class="header">
    <h1>📊 Marketing Strategy Report</h1>
    <div class="meta">
      🏢 <strong>{business_name}</strong> · {industry} · Stage: {stage}<br>
      📅 {date}
    </div>
    <div class="powered">Powered by Max — AI CMO · Marketing OS</div>
  </div>

  {sections_html}

  <div class="footer">
    Generated by <strong>Max — AI CMO</strong> · Marketing OS<br>
    Phân tích dựa trên thông tin business + framework KPI / SAVE / SMART<br>
    Không phải lời khuyên đầu tư — cross-check thực tế trước khi quyết định lớn
  </div>

</div>
</body>
</html>"""


def _md_to_html(text: str) -> str:
    """Convert markdown → HTML. Falls back to <pre> if no markdown lib available."""
    if not text:
        return ""
    if HAS_MARKDOWN:
        return _md.markdown(text, extensions=["tables", "fenced_code", "nl2br", "sane_lists"])
    # Fallback: basic conversion
    out = text
    out = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", out)
    out = re.sub(r"\*(.+?)\*", r"<em>\1</em>", out)
    out = out.replace("\n\n", "</p><p>")
    out = out.replace("\n", "<br>")
    return f"<p>{out}</p>"


def parse_agent_output(text: str) -> dict:
    """Extract structured sections from agent output.
    Returns {insight, summary, benchmarks, detail} — all strings (markdown)."""
    result = {"insight": "", "summary": "", "benchmarks": "", "detail": ""}

    patterns = {
        "insight":    r"##\s*💡[^\n]*\n+(.*?)(?=\n##\s|\Z)",
        "summary":    r"##\s*🎯[^\n]*\n+(.*?)(?=\n##\s|\Z)",
        "benchmarks": r"##\s*📊[^\n]*\n+(.*?)(?=\n##\s|\Z)",
        "detail":     r"##\s*📄[^\n]*\n+(.*?)(?=\n##\s|\Z)",
    }
    for key, pat in patterns.items():
        m = re.search(pat, text, flags=re.DOTALL)
        if m:
            result[key] = m.group(1).strip()

    # Fallback: if nothing parsed, treat all as detail
    if not any(result.values()):
        result["detail"] = text.strip()

    return result


def render_stage_html(stage_key: str, parsed: dict) -> str:
    """Render one stage as HTML section."""
    meta = STAGE_META.get(stage_key, {"title": stage_key, "icon": "📄", "color": ""})

    parts = []
    if parsed.get("insight"):
        # Strip wrapping quotes if present
        insight = parsed["insight"].strip().strip('"').strip("'")
        parts.append(f'<div class="insight">{_md_to_html(insight)}</div>')
    if parsed.get("summary"):
        parts.append('<div class="summary"><div class="summary-label">Tóm tắt</div>'
                     f'{_md_to_html(parsed["summary"])}</div>')
    if parsed.get("benchmarks"):
        parts.append('<div class="benchmarks"><div class="benchmarks-label">Benchmarks</div>'
                     f'{_md_to_html(parsed["benchmarks"])}</div>')
    if parsed.get("detail"):
        parts.append(f'<div class="content">{_md_to_html(parsed["detail"])}</div>')

    body = "\n".join(parts)
    return f"""
<div class="section {meta['color']}">
  <div class="section-header">
    <span class="icon">{meta['icon']}</span>
    <h2>{meta['title']}</h2>
  </div>
  {body}
</div>"""


def build_report(
    business_name: str,
    industry: str,
    stage: str,
    parsed_stages: list[tuple[str, dict]],
) -> str:
    """Render full HTML report.
    parsed_stages: list of (stage_key, parsed_dict) in pipeline order."""
    sections_html = "\n".join(render_stage_html(k, p) for k, p in parsed_stages)
    return HTML_TEMPLATE.format(
        business_name=business_name or "Business",
        industry=industry or "—",
        stage=stage or "—",
        date=datetime.now().strftime("%d/%m/%Y · %H:%M"),
        sections_html=sections_html,
        css=CSS,
    )
